---

- name: Configure shell environment
  ansible.builtin.include_tasks: shell.yml

- name: Install nvm
  ansible.builtin.include_tasks: nvm.yml

- name: Install pnpm
  ansible.builtin.include_tasks: pnpm.yml

- name: Install rustup
  ansible.builtin.include_tasks: rust.yml

- name: Install opencode
  ansible.builtin.include_tasks: opencode.yml

- name: Install sdkman
  ansible.builtin.include_tasks: sdkman.yml
