---

- name: Install rustup
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  become: true
  become_user: "{{ atomik_user }}"
  args:
    creates: "/var/home/{{ atomik_user }}/.cargo/bin/cargo"

- name: Deploy cargo shell config (Bash)
  ansible.builtin.copy:
    dest: "/var/home/{{ atomik_user }}/.bashrc.d/cargo.sh"
    owner: "{{ atomik_user }}"
    group: "{{ atomik_user }}"
    mode: "0644"
    content: |
      if [ -f "$HOME/.cargo/env" ]; then
          . "$HOME/.cargo/env"
      fi

- name: Deploy cargo shell config (Fish)
  ansible.builtin.copy:
    dest: "/var/home/{{ atomik_user }}/.config/fish/conf.d/cargo.fish"
    owner: "{{ atomik_user }}"
    group: "{{ atomik_user }}"
    mode: "0644"
    content: |
      if test -d "$HOME/.cargo/bin"
          fish_add_path "$HOME/.cargo/bin"
      end
